### ISSUE TITLE
Feature request: Make radar configurable

### ISSUE THREAD

**Issue by mkaito** [ChurchOrganist/Long_Range_Radar#1]
Hey!

I think it would be nice to be able to configure the radar power. That is, the size of the scanned and revealed areas, as well as the power cost and recipe cost.

There are two ways I can think of:

* Separate settings for each of those.
* A single "multiplier" setting that adjusts all of them at once.

I would also like to see the advanced radar consume regular radars as part of the recipe.

**Comment by ChurchOrganist** [comment]
Thank you for your input :)

I think configurable settings would stray too far from the original intention of the mod which is to provide extended coverage when using RSO. There is a distinct danger of the mod becoming far to OP and cheaty if made configurable.

Given that Advanced Radar is early game Tech - as soon as you have green science, I don't see the need for it to consume radars - most people won't have built many normal radars by that stage so there won't be mountains of them to reclaim. It would only complicate the supply chain, requiring 2 assemblers instead of one to make them.

Feel free to fork if you want to produce a configurable version - licence is MIT, so as long as you include the LICENSE.MD file in the zip you are free to do what you want to with the code.

**Comment by mkaito** [comment]
Fair enough. Looking forward to the update for 0.16 😄
